
function getBlogdir {
	cmd="import datetime as d;x=d.datetime.now();print(str(x.year)+'/'+str(x.month)+'/'+str(x.day))"
	python3 -c "$cmd"
	return 0
}
function mkblogdirAndCd {
	local dir title
	dir=$(getBlogdir)
	title="blog"
	if [ ! -z $1 ];then
		title="$1"
	fi
	mkdir -p "$dir" && cd "$dir" && vim "$title" && return 0
	return 1
}

function lsblogDir {
	dir=$(getBlogdir)
	echo "@@@@===  $dir"
	ls $dir
}
